[package]
name = "game3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "game3"
path = "src/lib.rs"

[dependencies]
